# Generated by Django 4.2.27 on 2026-05-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name or emoji for the category",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Question"),
                            ("image", "Image Question"),
                            ("quote", "Quote Question"),
                            ("emoji", "Emoji Clues"),
                            ("audio", "Audio Question"),
                            ("silhouette", "Silhouette Question"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="question type",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="The question or clue to display",
                        verbose_name="question text",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        help_text="The correct answer (movie/show title, actor name, etc.)",
                        max_length=255,
                        verbose_name="correct answer",
                    ),
                ),
                (
                    "alternative_answers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of acceptable alternative answers for fuzzy matching",
                        verbose_name="alternative answers",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for image-based questions",
                        verbose_name="image URL",
                    ),
                ),
                (
                    "emoji_clues",
                    models.CharField(
                        blank=True,
                        help_text="Emoji sequence representing the answer",
                        max_length=100,
                        verbose_name="emoji clues",
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="URL for audio-based questions",
                        verbose_name="audio URL",
                    ),
                ),
                (
                    "hint_1",
                    models.CharField(
                        blank=True,
                        help_text="First hint (e.g., release year)",
                        max_length=255,
                        verbose_name="hint 1",
                    ),
                ),
                (
                    "hint_2",
                    models.CharField(
                        blank=True,
                        help_text="Second hint (e.g., genre)",
                        max_length=255,
                        verbose_name="hint 2",
                    ),
                ),
                (
                    "hint_3",
                    models.CharField(
                        blank=True,
                        help_text="Third hint (e.g., director/lead actor)",
                        max_length=255,
                        verbose_name="hint 3",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="difficulty",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True,
                        help_text="Fun fact or explanation shown after answering",
                        verbose_name="explanation",
                    ),
                ),
                (
                    "times_shown",
                    models.PositiveIntegerField(default=0, verbose_name="times shown"),
                ),
                (
                    "times_correct",
                    models.PositiveIntegerField(
                        default=0, verbose_name="times correct"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="quizzes.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Quiz"),
                            ("blitz", "Fast Blitz"),
                            ("practice", "Practice Mode"),
                            ("challenge", "Weekly Challenge"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="quiz type",
                    ),
                ),
                (
                    "time_limit_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time limit for timed quizzes (null = no limit)",
                        null=True,
                        verbose_name="time limit (seconds)",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=6,
                        help_text="Maximum guesses per question (Wordle-style)",
                        verbose_name="max attempts",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
                (
                    "publish_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this quiz becomes available",
                        null=True,
                        verbose_name="publish date",
                    ),
                ),
                (
                    "times_played",
                    models.PositiveIntegerField(default=0, verbose_name="times played"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="quizzes.category",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "quiz",
                "verbose_name_plural": "quizzes",
                "ordering": ["-publish_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizzes.question",
                        verbose_name="question",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizzes.quiz",
                        verbose_name="quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "quiz question",
                "verbose_name_plural": "quiz questions",
                "ordering": ["order"],
                "unique_together": {("quiz", "question")},
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="questions",
            field=models.ManyToManyField(
                related_name="quizzes",
                through="quizzes.QuizQuestion",
                to="quizzes.question",
                verbose_name="questions",
            ),
        ),
        migrations.CreateModel(
            name="DailyPuzzle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="The date this puzzle is active",
                        unique=True,
                        verbose_name="date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this daily puzzle is currently active",
                        verbose_name="active",
                    ),
                ),
                (
                    "total_attempts",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total attempts"
                    ),
                ),
                (
                    "total_completions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total completions"
                    ),
                ),
                (
                    "average_score",
                    models.FloatField(default=0.0, verbose_name="average score"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_schedules",
                        to="quizzes.quiz",
                        verbose_name="quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily puzzle",
                "verbose_name_plural": "daily puzzles",
                "ordering": ["-date"],
            },
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["quiz_type"], name="quizzes_qui_quiz_ty_c4ea4e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["publish_date"], name="quizzes_qui_publish_aec786_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(
                fields=["is_published"], name="quizzes_qui_is_publ_8ea5d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type"], name="quizzes_que_questio_7af5f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["difficulty"], name="quizzes_que_difficu_79adbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_active"], name="quizzes_que_is_acti_33f27d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailypuzzle",
            index=models.Index(fields=["date"], name="quizzes_dai_date_8b79ad_idx"),
        ),
        migrations.AddIndex(
            model_name="dailypuzzle",
            index=models.Index(
                fields=["is_active"], name="quizzes_dai_is_acti_1c3a21_idx"
            ),
        ),
    ]
