# Generated by Django 4.2.27 on 2026-05-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tmdb_id",
                    models.PositiveBigIntegerField(unique=True, verbose_name="TMDb id"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("movie", "Movie"), ("tv", "TV Show")],
                        default="movie",
                        max_length=10,
                        verbose_name="kind",
                    ),
                ),
                (
                    "canonical_title",
                    models.CharField(max_length=255, verbose_name="canonical title"),
                ),
                (
                    "normalized_title",
                    models.CharField(
                        db_index=True,
                        help_text="Lowercased, accent-stripped, used for autocomplete prefix match.",
                        max_length=255,
                        verbose_name="normalized title",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="year"
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Alternate titles + abbreviations a player might type.",
                        verbose_name="aliases",
                    ),
                ),
                (
                    "popularity",
                    models.FloatField(default=0.0, verbose_name="popularity"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "title",
                "verbose_name_plural": "titles",
                "ordering": ["-popularity", "canonical_title"],
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="mode",
            field=models.CharField(
                choices=[
                    ("synopsis_ladder", "Synopsis Ladder"),
                    ("cast_ladder", "Cast Ladder"),
                    ("quote", "Quote of the Day"),
                    ("emoji_rebus", "Emoji Rebus"),
                    ("trio", "Year-Genre-BoxOffice Trio"),
                    ("decade_director", "Decade and Director"),
                ],
                default="synopsis_ladder",
                help_text="Puzzle mechanic. Each mode reuses the same submit/results plumbing with a different clue ladder shape.",
                max_length=32,
                verbose_name="puzzle mode",
            ),
        ),
        migrations.AddIndex(
            model_name="quiz",
            index=models.Index(fields=["mode"], name="quizzes_qui_mode_62e7df_idx"),
        ),
        migrations.AddIndex(
            model_name="title",
            index=models.Index(
                fields=["normalized_title"], name="quizzes_tit_normali_668e7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="title",
            index=models.Index(
                fields=["popularity"], name="quizzes_tit_popular_b6c6cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="title",
            index=models.Index(fields=["kind"], name="quizzes_tit_kind_f6122a_idx"),
        ),
    ]
