# Generated by Django 4.2.27 on 2026-05-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_title_quiz_mode_quiz_quizzes_qui_mode_62e7df_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailypuzzle",
            name="gemini_model_name",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="gemini model name"
            ),
        ),
        migrations.AddField(
            model_name="dailypuzzle",
            name="gemini_prompt_version",
            field=models.CharField(
                blank=True,
                default="",
                max_length=16,
                verbose_name="gemini prompt version",
            ),
        ),
        migrations.AddField(
            model_name="dailypuzzle",
            name="gemini_raw_response",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Full Gemini candidate JSON for this puzzle.",
                verbose_name="gemini raw response",
            ),
        ),
        migrations.AddField(
            model_name="dailypuzzle",
            name="tmdb_overview_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 of the synopsis text used as the Gemini input.",
                max_length=64,
                verbose_name="source overview hash",
            ),
        ),
    ]
