# Generated by Django 4.2.27 on 2026-05-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_dailypuzzle_gemini_model_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("movie", "Movie only"),
                    ("tv", "TV show only"),
                    ("any", "Either movie or TV"),
                ],
                default="any",
                help_text="If 'movie' or 'tv', the answer combobox only suggests titles of that kind. Keeps players from wading through irrelevant matches.",
                max_length=10,
                verbose_name="target answer kind",
            ),
        ),
    ]
