# Generated by Django 4.2.27 on 2026-05-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0004_question_target_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="target_kind",
            field=models.CharField(
                choices=[("movie", "Movie only"), ("tv", "TV show only")],
                default="movie",
                help_text="The answer combobox only suggests titles of this kind. Must be 'movie' or 'tv'.",
                max_length=10,
                verbose_name="target answer kind",
            ),
        ),
    ]
