# Generated by Django 4.2.27 on 2026-05-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0006_coerce_any_target_kind_to_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="target_kind",
            field=models.CharField(
                choices=[
                    ("movie", "Movie"),
                    ("tv", "TV show"),
                    ("any", "Unclassified — not eligible for daily quiz"),
                ],
                default="any",
                help_text="Set to 'movie' or 'tv' once the answer is verified. The daily quiz endpoint only serves verified questions; 'any' is a review queue, not a permissive default.",
                max_length=10,
                verbose_name="target answer kind",
            ),
        ),
    ]
