# Generated by Django 4.2.27 on 2026-05-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for anonymous user device",
                        unique=True,
                        verbose_name="device ID",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="first seen"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="last seen"),
                ),
                (
                    "timezone_name",
                    models.CharField(
                        default="UTC",
                        help_text="User's timezone for daily puzzle timing",
                        max_length=50,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=False, verbose_name="notifications enabled"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anonymous_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registered user",
                    ),
                ),
            ],
            options={
                "verbose_name": "anonymous user",
                "verbose_name_plural": "anonymous users",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="started at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="completed"),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of correct answers",
                        verbose_name="score",
                    ),
                ),
                (
                    "total_questions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total questions"
                    ),
                ),
                (
                    "attempts_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of guess attempts made",
                        verbose_name="attempts used",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=list,
                        help_text="List of answers given with correctness",
                        verbose_name="answers",
                    ),
                ),
                (
                    "time_taken_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="time taken (seconds)"
                    ),
                ),
                (
                    "anonymous_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_progress",
                        to="analytics.anonymoususer",
                        verbose_name="anonymous user",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="quizzes.quiz",
                        verbose_name="quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registered user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user progress",
                "verbose_name_plural": "user progress records",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Streak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_streak",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current consecutive days played",
                        verbose_name="current streak",
                    ),
                ),
                (
                    "best_streak",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Longest streak ever achieved",
                        verbose_name="best streak",
                    ),
                ),
                (
                    "last_played_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last quiz completion",
                        null=True,
                        verbose_name="last played date",
                    ),
                ),
                (
                    "streak_freezes_available",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of streak freeze tokens available",
                        verbose_name="streak freezes available",
                    ),
                ),
                (
                    "streak_freezes_earned",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of streak freezes earned from milestones",
                        verbose_name="streak freezes earned",
                    ),
                ),
                (
                    "streak_freeze_used_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="streak freeze used date"
                    ),
                ),
                (
                    "total_days_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total days played"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "anonymous_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to="analytics.anonymoususer",
                        verbose_name="anonymous user",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registered user",
                    ),
                ),
            ],
            options={
                "verbose_name": "streak",
                "verbose_name_plural": "streaks",
                "ordering": ["-current_streak"],
            },
        ),
        migrations.CreateModel(
            name="DailyQuizStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique_for_date="quiz", verbose_name="date")),
                (
                    "total_attempts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of times the quiz was started",
                        verbose_name="total attempts",
                    ),
                ),
                (
                    "total_completions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of times the quiz was completed",
                        verbose_name="total completions",
                    ),
                ),
                (
                    "average_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Average score across all completions",
                        verbose_name="average score",
                    ),
                ),
                (
                    "total_score",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sum of all scores for calculating average",
                        verbose_name="total score",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="quizzes.quiz",
                        verbose_name="quiz",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily quiz stats",
                "verbose_name_plural": "daily quiz stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_quizzes_played",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total quizzes played"
                    ),
                ),
                (
                    "total_quizzes_completed",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total quizzes completed"
                    ),
                ),
                (
                    "total_questions_answered",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total questions answered"
                    ),
                ),
                (
                    "total_correct_answers",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total correct answers"
                    ),
                ),
                (
                    "perfect_scores",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of quizzes with 100% score",
                        verbose_name="perfect scores",
                    ),
                ),
                (
                    "total_score",
                    models.PositiveIntegerField(default=0, verbose_name="total score"),
                ),
                (
                    "average_score",
                    models.FloatField(default=0.0, verbose_name="average score"),
                ),
                (
                    "best_score",
                    models.PositiveIntegerField(default=0, verbose_name="best score"),
                ),
                (
                    "fastest_completion_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="fastest completion (seconds)",
                    ),
                ),
                (
                    "average_completion_seconds",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="average completion (seconds)",
                    ),
                ),
                (
                    "global_rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="global rank"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "anonymous_user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="analytics.anonymoususer",
                        verbose_name="anonymous user",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registered user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user stats",
                "verbose_name_plural": "user stats",
                "ordering": ["-total_score"],
                "indexes": [
                    models.Index(
                        fields=["total_score"], name="analytics_u_total_s_bdb9e0_idx"
                    ),
                    models.Index(
                        fields=["global_rank"], name="analytics_u_global__e8cf7f_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userstats",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("anonymous_user__isnull", False), ("user__isnull", True)),
                    models.Q(("anonymous_user__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="stats_user_or_anonymous_required",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["anonymous_user", "quiz"], name="analytics_u_anonymo_3c54a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "quiz"], name="analytics_u_user_id_f9936d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["is_completed"], name="analytics_u_is_comp_1a4584_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="userprogress",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("anonymous_user__isnull", False), ("user__isnull", True)),
                    models.Q(("anonymous_user__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="user_or_anonymous_required",
            ),
        ),
        migrations.AddIndex(
            model_name="streak",
            index=models.Index(
                fields=["current_streak"], name="analytics_s_current_c46b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="streak",
            index=models.Index(
                fields=["best_streak"], name="analytics_s_best_st_f6b53b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="streak",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("anonymous_user__isnull", False), ("user__isnull", True)),
                    models.Q(("anonymous_user__isnull", True), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="streak_user_or_anonymous_required",
            ),
        ),
        migrations.AddIndex(
            model_name="dailyquizstats",
            index=models.Index(
                fields=["date", "quiz"], name="analytics_d_date_e1fd0c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyquizstats",
            constraint=models.UniqueConstraint(
                fields=("date", "quiz"), name="unique_daily_quiz_stats"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymoususer",
            index=models.Index(
                fields=["device_id"], name="analytics_a_device__63d9dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="anonymoususer",
            index=models.Index(fields=["user"], name="analytics_a_user_id_86ffb5_idx"),
        ),
    ]
