# Generated by Django 4.2.27 on 2026-05-01 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                blank=True,
                help_text="Friends for social leaderboards and challenges",
                related_name="friend_of",
                to=settings.AUTH_USER_MODEL,
                verbose_name="friends",
            ),
        ),
    ]
